export const attendanceConstants = {
    ATTENDANCE_SHOW: 'ATTENDANCE_SHOW',
    ATTENDANCE_NEW: 'ATTENDANCE_NEW',
    ATTENDANCE_DELETE: 'ATTENDANCE_DELETE',
    ATTENDANCE_UPDATE: 'ATTENDANCE_UPDATE'
};