export const notificationConstants = {
    NOTIFICATION_SHOW: 'NOTIFICATION_SHOW',
    NOTIFICATION_NEW: 'NOTIFICATION_NEW',
    NOTIFICATION_DELETE: 'NOTIFICATION_DELETE',
    NOTIFICATION_UPDATE: 'NOTIFICATION_UPDATE'
};